[workspace]
members = [ "common", "vmm", "kernel", "macros" , "user", "arca" , "arcade" , "ninep", "arcane", "vfs" , "memcached", "thumbnail-example", "fix", "memfs"]
default-members = [ "vmm", "common" ]

resolver = "2"

[profile.release]
debug = true
