[workspace]
members = [ "common", "vmm", "kernel", "macros" , "user", "arca" , "arcade" , "ninep", "arcane", "vfs" , "fix" ]
default-members = [ "vmm", "common" ]

resolver = "2"

[profile.release]
debug = true
