[workspace]
members = [ "common", "vmm", "kernel", "macros" , "user", "arca" , "arcade" , "ninep", "arcane", "vfs" , "memcached", "fix", "wasi" ]
default-members = [ "vmm", "common" ]

resolver = "2"

# [profile.release]
# debug = true
