[workspace]
members = [ "common", "vmm", "kernel", "macros" , "user", "arca" , "arcane", "fix", "fix/runtime", "fix/handle", "fix/shell" ]
default-members = [ "common", "vmm", "macros", "arca" ]

resolver = "2"

[profile.release]
debug = true
