cargo-features = ["per-package-target"]

[package]
name = "fixhandle"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", default-features = false, features = ["full"] }
macros = { path = "../../macros" }

[features]
testing-mode = []
