[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro-crate = "3.1.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.67", features = ["full"] }

[lib]
proc-macro = true

[features]
default = []
