name: Build Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-none
        components: rustfmt
    - name: Check Formatting
      run: cargo fmt --check
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-none
        components: clippy
    - name: Setup
      run: |
        sudo apt update && sudo apt install gcc-multilib
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-29/wasi-sdk-29.0-x86_64-linux.tar.gz
        tar xvf wasi-sdk-29.0-x86_64-linux.tar.gz
        echo WASI_SDK_PATH=`pwd`/wasi-sdk-29.0-x86_64-linux | sudo tee -a $GITHUB_ENV
    - name: Prebuild arca-musl
      run: |
        pushd modules/arca-musl
        ./configure
        make -j4
        popd
    - name: Clippy
      run: cargo clippy --all-features
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-none
    - name: Setup
      run: |
        sudo apt update && sudo apt install gcc-multilib
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-29/wasi-sdk-29.0-x86_64-linux.tar.gz
        tar xvf wasi-sdk-29.0-x86_64-linux.tar.gz
        echo WASI_SDK_PATH=`pwd`/wasi-sdk-29.0-x86_64-linux | sudo tee -a $GITHUB_ENV
        sudo modprobe vhost_vsock
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system
        sudo usermod -a -G kvm,libvirt $USER
    - name: Prebuild arca-musl
      run: |
        pushd modules/arca-musl
        ./configure
        make -j4
        popd
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: |
        sudo --preserve-env=WASI_SDK_PATH -su $USER /home/runner/.cargo/bin/cargo test --verbose
